# Generated by Django 3.2 on 2023-03-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_brith',
            new_name='date_of_birth',
        ),
    ]
